site_name: XLiu CS Blog
site_description: Compute Science Blog
site_author: LiuZhiqiang(刘志强）
site_url: https://xliuqq.github.io/csblog
repo_url: https://github.com/xliuqq/csblog
repo_name: xliuqq/csblog
docs_dir: docs
site_dir: site
 
use_directory_urls: false
exclude_docs: |
  !.pics
  
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
  language: 'zh'
  icon:
    repo: fontawesome/brands/github
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes

extra:
  github_repo: xliuqq/csblog
  
plugins:
  - search
  - blog:
      blog_dir: ./
      categories: true
  - tags:
      tags_file: tags.md
extra_javascript:
  - .mkdocs/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

nav:
  - 博客:
    - index.md
    - 标签: tags.md
  - 云原生:
    - 概述: cloud/README.md
    - 虚拟化: 
      - 概述: cloud/virtualize/README.md
      - proc虚拟化和共享: cloud/virtualize/lxcfs.md
      - gpu虚拟化: cloud/virtualize/gpu.md
      - moby(docker): 
        - 基础: cloud/virtualize/docker.md
        - 部署配置: cloud/virtualize/docker_deploy.md
        - 使用: cloud/virtualize/docker_cmds.md
      - containerd: cloud/virtualize/containerd.md
    - k8s:
      - 架构与组件:
        - 概述: cloud/k8s/k8s.md
        - kubelet: cloud/k8s/kubelet.md
      - 对象定义: cloud/k8s/k8s_object.md
      - 内置资源对象: cloud/k8s/k8s_resource.md
      - pod原地升级: cloud/k8s/pod_inplace_upgrade.md
      - 常用配置: cloud/k8s/config.md
      - 命令使用: cloud/k8s/cmds.md
      - goclient: cloud/k8s/go_client.md
      - UI和管理: cloud/k8s/ui_manager.md
      - 日志架构: cloud/k8s/log_arch.md
      - 安全机制: cloud/k8s/k8s_security.md
      - 资源调度:
        - 调度策略: cloud/k8s/scheduler.md
        - 调度策略: cloud/k8s/scheduler_plugin.md
      - CRD:
        - 概述: cloud/k8s/crd_index.md
        - kubebuilder: cloud/k8s/crd_kubebuilder.md
        - JavaOperator: cloud/k8s/crd_java.md
      - 指标监控: cloud/k8s/metrics.md
      - 设备插件: cloud/k8s/device_plugin.md
      - 垃圾回收: cloud/k8s/garbage_collect.md
      - Wehhook: cloud/k8s/webhook.md
      - 网络模型: cloud/k8s/network.md
      - 存储模型: cloud/k8s/extend_csi.md
      - 安装部署: 
        - 部署流程: cloud/k8s/deploy.md
        - 存储部署: cloud/k8s/deploy_storage.md
      - 生产注意事项: cloud/k8s/notes.md
      - 可选发行版: cloud/k8s/release_compare.md
    - 包管理Helm: cloud/helm.md
    - 镜像仓库Habor: cloud/habor.md
    - 无服务化:
      - 概述: cloud/serverless/serverless.md
      - knative: cloud/serverless/knative.md
      - openfaas: cloud/serverless/openfaas.md
    - 常用镜像:
      - 常用镜像: cloud/images/images.md
      - 浏览器centos: cloud/images/web_centos.md
    - 镜像工具: cloud/tools.md
    - 云边系统:
      - mqtt协议: cloud/cloud_edge/mqtt.md
      - openyurt: cloud/cloud_edge/openyurt.md
      - kubeedge: cloud/cloud_edge/kubeedge.md
    - 项目:
      - vGPU HAMI: cloud/projects/HAMi.md
      - 数据编排Fluid: cloud/projects/fluid.md
      - 流量编排Istio: cloud/projects/istio.md
      - 应用交付KubeVela: cloud/projects/kubevela.md
  - 书籍:
    - books/index.md
    - 数据密集型系统设计: 
      - books/data_intensive_system_book/README.md
      - books/data_intensive_system_book/1_data_system_basic.md
      - books/data_intensive_system_book/2_data_model_query_language.md
      - books/data_intensive_system_book/3_data_store_and_search.md
      - books/data_intensive_system_book/4_encoding_and_evolution.md
      - books/data_intensive_system_book/part2_distributed_data.md
      - books/data_intensive_system_book/5_replication.md
      - books/data_intensive_system_book/6_partitions.md
      - books/data_intensive_system_book/7_transaction.md
      - books/data_intensive_system_book/8_trouble_in_distributed_system.md
      - books/data_intensive_system_book/9_consistency_consensus.md
      - books/data_intensive_system_book/part3_derived_data.md
      - books/data_intensive_system_book/10_batch_processing.md
      - books/data_intensive_system_book/11_streaming_processing.md
      - books/data_intensive_system_book/12_the_future.md
  - 编程指南:
    - 设计原则: code_guide/design_principle.md
    - 设计模式: 
      - 导览: code_guide/design_pattern/README.md
      - 创建型模式:
        - 工厂模式: code_guide/design_pattern/factory.md
        - 抽象工厂: code_guide/design_pattern/abstract_factory.md
        - 单例: code_guide/design_pattern/singleton.md
        - 构造者模式: code_guide/design_pattern/builder.md
        - 原型模式: code_guide/design_pattern/prototype.md
      - 结构型模式:
        - 适配器模式: code_guide/design_pattern/adapter.md
        - 桥接模式: code_guide/design_pattern/bridge.md
        - 组合模式: code_guide/design_pattern/composite.md
        - 装饰模式: code_guide/design_pattern/decorator.md
        - 外观模式: code_guide/design_pattern/facade.md
        - 享元模式: code_guide/design_pattern/flyweight.md
        - 代理模式: code_guide/design_pattern/proxy.md
      - 行为型模式:
        - 职责链模式: code_guide/design_pattern/chain.md
        - 命令模式: code_guide/design_pattern/command.md
        - 解释器模式: code_guide/design_pattern/interpret.md
        - 迭代器模式: code_guide/design_pattern/iterator.md
        - 中介者模式: code_guide/design_pattern/medium.md
        - 备忘录模式: code_guide/design_pattern/memento.md
        - 观察者模式: code_guide/design_pattern/observer.md
        - 状态模式: code_guide/design_pattern/state.md
        - 策略模式: code_guide/design_pattern/strategy.md
        - 模板方法: code_guide/design_pattern/template.md
        - 访问者模式: code_guide/design_pattern/visitor.md
      - 分布式应用设计模式: code_guide/design_pattern/container_distributed.md
  - 编程语言:
    - Java:
      - Native: 
        - 概览: languages/java/native/README.md
        - JNI: 
          - 原理: languages/java/native/jni.md
          - 示例: languages/java/native/jni_demo.md
        - JNR: languages/java/native/jnr.md
    - C和C++:
      - 基础: languages/ccpp/basic.md
      - 类: languages/ccpp/class.md
      - 并发: languages/ccpp/concurrency.md
      - 调试: languages/ccpp/debug.md
      - CallPython: languages/ccpp/call_python.md
      - ABI: languages/ccpp/abi.md
      - gcc: languages/ccpp/gcc.md
      - make: languages/ccpp/make.md
    - ffi: languages/libffi.md
    - unicode: languages/unicode.md
    - 语言自举: languages/ziju.md
  - linux:
    - 基础: linux/basic.md
    - shell编程: linux/shell_programming.md
    - 性能调试命令: linux/tuning.md
    - bash: linux/bash.md
    - chmod: linux/chmod.md
    - chroot: linux/chroot.md
    - gnu工具: linux/binutils.md
    - 防火墙: linux/firewall.md
    - 名空间: linux/namespace.md
    - cgroup: linux/cgroup.md
    - 进程的限制: linux/limit_process.md
    - systemctl: linux/systemctl.md
    - 日志管理: linux/log_and_rotate.md
    - 进程快照: linux/process_snapshot.md
    - acls: linux/acls.md
    - 网络: linux/network.md
    - 文件系统: linux/fs.md
    - 零拷贝: linux/zero_copy.md
    - 源配置: linux/yum.md

  - Web后端开发:
    - 总览: web_backend/README.md
    - 切面编程(Java): web_backend/aop_java.md
    - 缓存: web_backend/cache.md
  - CS基础:
    - 基础: cs/cs_basic.md
    - 操作系统: cs/cs_os.md
    - 网络:
      - 概述: cs/network/README.md
      - 网络层协议: cs/network/network.md
      - 传输层协议: cs/network/trans_protocols.md
      - HTTP: cs/network/http.md
      - 内网穿透: cs/network/intranet_penetration.md
      - LVS: cs/network/LVS.md
  - 课程:
    - 操作系统设计与实现(2023): 
      - 0.整体大纲: courses/os_lab/README.md
      - 1.操作系统概述: courses/os_lab/01-os_introduction.md
      - 2.应用视角的操作系统: courses/os_lab/02-os_appview.md
      - 3.硬件视角的操作系统: courses/os_lab/03-os_hardware_view.md
      - 4.Python 建模操作系统: courses/os_lab/04-os_python_modeling.md
      - 5.多处理器编程：从入门到放弃: courses/os_lab/05_multi_cpu_programming.md
      - 6.应用视角的操作系统: courses/os_lab/06_concurrent_control_basic.md
      - 7.并发控制：互斥: courses/os_lab/07_concurrent_control_mutex.md
      - 8.调试理论与实践: courses/os_lab/08_debug_and_action.md
      - 9.并发控制：同步（条件变量）: courses/os_lab/09_sync_condition.md
      - 10.并发控制：同步（信号量）: courses/os_lab/10_sync_semphore.md
      - 11.真实世界的并发编程: courses/os_lab/11_concurrent_in_real_world.md
      - 12.并发BUG分类: courses/os_lab/12_concurrent_bug_category.md
      - 13.并发 Bug 的应对: courses/os_lab/13_concurrent_bug_defense.md
      - 14.多处理器系统与中断机制: courses/os_lab/14_multi_cpu_and_interrupt.md
      - 15.操作系统上的进程: courses/os_lab/15_kernel_thread_and_process.md
      - 16.Linux 操作系统: courses/os_lab/16_application_in_linux.md
      - 17.Linux 进程的地址空间: courses/os_lab/17_hack_linux_process_address.md
      - 18.操作系统实验生存指南: courses/os_lab/18_os_lab_live_guide.md
      - 19.系统调用和 UNIX Shell: courses/os_lab/19_system_call_and_shell.md
      - 20.C标准库和实现: courses/os_lab/20-c_standard_lib.md
      - 21-22.可执行文件与加载: courses/os_lab/21-22-executable_files_loading.md
      - 23.状态机模型的应用: courses/os_lab/23_application_of_state_machine.md
      - 24.操作系统进程的实现 : courses/os_lab/24_impletation_of_os_process.md
      - 25.存储设备原理: courses/os_lab/25_store_device.md
      - 26.输入输出设备: courses/os_lab/26_input_output_device.md
      - 27.设备驱动程序与文件系统: courses/os_lab/27_device_driver_and_filesystem.md
      - 28.FAT 和 UNIX 文件系统: courses/os_lab/28_FAT_UNIX_filesystem.md
      - 29.持久数据的可靠性: courses/os_lab/29_available_durable_data.md
      - 30.课程总结: courses/os_lab/30_summarize.md

  - 论文:
    - go并发bugs: paper/go_concurrency_bugs.md
    - HPC中的作业调度: paper/job_scheduling_in_hpc.md
    - 可扩展性的代价: paper/scalability_but_at_what_cost.md