site_name: XLiu CS Blog
site_description: Compute Science Blog
site_author: LiuZhiqiang(刘志强）
site_url: https://xliuqq.github.io/csblog
repo_url: https://github.com/xliuqq/csblog
repo_name: xliuqq/csblog
docs_dir: docs
site_dir: site
 
use_directory_urls: false
  
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  language: 'zh'
  icon:
    repo: fontawesome/brands/github
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 

extra:
  github_repo: xliuqq/csblog
  
plugins:
  - search
  - blog:
      blog_dir: ./
      categories: true
  - tags:
      tags_file: tags.md
extra_javascript:
  - .mkdocs/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

nav:
  - 博客:
    - index.md
    - 标签: tags.md
  - 数据密集型系统设计: 
    - data_intensive_system_book/1_data_system_basic.md
    - data_intensive_system_book/2_data_model_query_language.md
    - data_intensive_system_book/3_data_store_and_search.md
  - 论文:
    - paper/go_concurrency_bugs.md